// app related
export const SYNC_HISTORY = 'SYNC_HISTORY'
export const SYNC_SETTINGS = 'SYNC_SETTINGS'
export const SET_ICON_MAP = 'SET_ICON_MAP'
export const SET_HISTORY = 'SET_HISTORY'
export const UPDATE_HISTORY = 'UPDATE_HISTORY'
export const CLEAR_HISTORY = 'CLEAR_HISTORY'
export const TOGGLE_SETTINGS = 'TOGGLE_SETTINGS'
export const SET_IS_MOBILE = 'SET_IS_MOBILE'
export const SET_IS_HOVERABLE = 'SET_IS_HOVERABLE'
export const ADD_BOOKMARK = 'ADD_BOOKMARK'
export const REMOVE_BOOKMARK = 'REMOVE_BOOKMARK'

// ui related
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER'
export const OPEN_DRAWER = 'OPEN_DRAWER'
export const HIDE_DRAWER = 'HIDE_DRAWER'
export const TOGGLE_SETTINGS_MODAL = 'TOGGLE_SETTINGS_MODAL'
export const TOGGLE_GALLERY = 'TOGGLE_GALLERY'
export const HIDE_GALLERY = 'HIDE_GALLERY'

// category related
export const SET_CATEGORY_LIST = 'SET_CATEGORY_LIST'
export const SET_FIXED_CATEGORY_LIST = 'SET_FIXED_CATEGORY_LIST'
export const SET_CATEGORY = 'SET_CATEGORY'

// thread list related
export const SET_THREAD_LIST_TYPE = 'SET_THREAD_LIST_TYPE'
export const SET_THREAD_LIST_IS_LOADING = 'SET_THREAD_LIST_IS_LOADING'
export const SET_THREAD_LIST_PAGE = 'SET_THREAD_LIST_PAGE'
export const SET_THREAD_LIST_HAS_MORE = 'SET_THREAD_LIST_HAS_MORE'
export const SET_THREAD_LIST = 'SET_THREAD_LIST'
export const APPEND_THREAD_LIST = 'APPEND_THREAD_LIST'

// thread related
export const SET_STORY_MODE = 'SET_STORY_MODE'
export const SET_THREAD_IS_LOADING = 'SET_THREAD_IS_LOADING'
export const SET_THREAD_PAGE = 'SET_THREAD_PAGE'
export const SET_THREAD = 'SET_THREAD'
export const APPEND_THREAD = 'APPEND_THREAD'
export const SET_IS_FETCHING_MEDIA = 'SET_IS_FETCHING_MEDIA'
export const SET_MEDIA_LIST = 'SET_MEDIA_LIST'
export const SET_MEDIA_INDEX = 'SET_MEDIA_INDEX'
