export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES'
export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY'

export const SET_LOADING_THRED_LIST = 'SET_LOADING_THRED_LIST'
export const RESET_THREADS = 'RESET_THREADS'
export const RECEIVE_THREAD_LIST = 'RECEIVE_THREAD_LIST'
export const RECEIVE_MORE_THREAD_LIST = 'RECEIVE_MORE_THREAD_LIST'
export const SET_HAS_MORE_THREADS = 'SET_HAS_MORE_THREADS'
export const SET_ACTIVE_THREAD = 'SET_ACTIVE_THREAD'

export const TOGGLE_WHITE_THEME = 'TOGGLE_WHITE_THEME'
export const TOGGLE_AUTO_LOAD_IMAGE = 'TOGGLE_AUTO_LOAD_IMAGE'
