// Category related
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES'
export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY'
export const SET_LOADING_THRED_LIST = 'SET_LOADING_THRED_LIST'
export const SET_REPLACING_THRED_LIST = 'SET_REPLACING_THRED_LIST'
export const RESET_THREADS = 'RESET_THREADS'
export const RECEIVE_THREAD_LIST = 'RECEIVE_THREAD_LIST'
export const RECEIVE_MORE_THREAD_LIST = 'RECEIVE_MORE_THREAD_LIST'
export const SET_HAS_MORE_THREADS = 'SET_HAS_MORE_THREADS'

// Thread related
export const SET_ACTIVE_THREAD = 'SET_ACTIVE_THREAD'
export const RESET_THREAD = 'RESET_THREAD'
export const SET_PHOTO_MODE = 'SET_PHOTO_MODE'

// Settings related
export const TOGGLE_WHITE_THEME = 'TOGGLE_WHITE_THEME'
export const TOGGLE_OFFICE_MODE = 'TOGGLE_OFFICE_MODE'
export const TOGGLE_AUTO_LOAD_IMAGE = 'TOGGLE_AUTO_LOAD_IMAGE'
export const TOGGLE_YOUTUBE_PREVIEW = 'TOGGLE_YOUTUBE_PREVIEW'
export const UPDATE_HISTORY = 'UPDATE_HISTORY'
export const SET_ICON_MAP = 'SET_ICON_MAP'
export const SET_THREAD_HISTORY = 'SET_THREAD_HISTORY'
export const RESET_THREAD_HISTORY = 'RESET_THREAD_HISTORY'
